--SKUH
SELECT P.YITMREF_0 AS Code_sku, K.ITMDES1_0 AS Nom_sku, 1 AS Code_marq, '0' AS pds_sousEmb, '0' AS nbr_sousEmb, '' AS dim_sousEmb, '' AS ref_sousEmb, CASE WHEN P.[PAL] IS NOT NULL AND C.[COL] IS NOT NULL 
                  THEN C.[COL] END AS pds_com, CASE WHEN P.[PAL] IS NOT NULL AND C.[COL] IS NOT NULL THEN C.[COL] * 1.02 END AS pds_pro, CASE WHEN P.[PAL] IS NOT NULL AND C.[COL] IS NOT NULL THEN P.PAL END AS nbr_col, 
                  CASE WHEN U.YFILM_0 LIKE '%2%' THEN 'Oui' ELSE 'Non' END AS Avec_film, S.LANMES_0 AS typcond, '0' AS cout_emb, CASE WHEN Z.USESTA_0 LIKE '%2%' THEN 'Oui' ELSE 'Non' END AS valide
FROM     dbo.YNPAL AS P INNER JOIN
                  dbo.YNCOL AS C ON P.YITMREF_0 = C.YITMREF_0 LEFT OUTER JOIN
                  dbo.YBAR AS B ON B.YITMREF_0 = C.YITMREF_0 INNER JOIN
                  DELADEV.ITMMASTER AS K ON P.YITMREF_0 = K.ITMREF_0 INNER JOIN
                  DELADEV.BOM AS Z ON P.YITMREF_0 = Z.ITMREF_0 INNER JOIN
                  dbo.YTYP AS S ON S.YPF1_0 = K.ITMREF_0 INNER JOIN
                  dbo.YPK AS U ON U.YPF1_0 = Z.ITMREF_0

--VARC

SELECT Code_sku, Code_art
FROM     dbo.YVPFV
WHERE  (Code_art LIKE 'VAR%')

--YBAR

SELECT YITMREF_0, YCOND_0 AS BAR
FROM     DELADEV.YCOUNIT AS U
WHERE  (YITMREF_0 LIKE 'PFV%') AND (YCOND_0 LIKE '%BAR%')

--[dbo].[YCOL]

SELECT YITMREF_0, CASE WHEN U.[YCOND_0] LIKE '%COL%' AND U.[YUNI_0] LIKE '%KG%' THEN U.[YVAL_0] END AS COL
FROM     DELADEV.YCOUNIT AS U
WHERE  (YITMREF_0 LIKE 'PFV%')



--[dbo].[YClient]

SELECT A.BPCNUM_0 AS Code_cli, A.BPCNAM_0 AS Nom_cli, B.CTY_0 AS Ville, B.CRYNAM_0 AS code_grp
FROM     DELADEV.BPCUSTOMER AS A INNER JOIN
                  DELADEV.BPADDRESS AS B ON A.BPCNUM_0 = B.BPANUM_0 AND A.BPAADD_0 = B.BPAADD_0
WHERE  (A.BCGCOD_0 LIKE 'CE')


--[dbo].[YD_SKUArticle]


SELECT ROW_NUMBER() OVER (ORDER BY P.[Code_sku]) AS ID, P.[Code_sku], P.[Nature], P.[Code_art], P.[qte_art], P.[destock], s.[VLTTOT_0] AS 'prix_ini', P.[prctg_maj]
FROM     YNPFV P INNER JOIN
                  DELADEV.ITMCOST AS s ON s.ITMREF_0 = P.[Code_art]
WHERE  s.STOFCY_0 LIKE 'STDU';

--[dbo].[YD_SKUVarCmr]


SELECT B.YPF1_0 AS Code_sku, CASE WHEN C.[YNV2_0] LIKE 'PACK%' THEN E.[YNP2_0] ELSE C.[YNV2_0] END AS Code_varCmr
FROM     DELADEV.YSKU AS C LEFT OUTER JOIN
                  DELADEV.YPACK AS E ON C.YNV2_0 = E.YNP1_0 INNER JOIN
                  DELADEV.YPFV AS B ON C.YNV1_0 = B.YPV2_0
WHERE  (C.YNV2_0 LIKE 'VAR%')


--YMagasinClient


SELECT N.BPAADD_0 AS Code_mgs, A.BPCNUM_0 AS Code_cli, B.BPAADDLIG_0 AS Adresse, B.CTY_0 AS ville, B.TEL_0 AS tele, B.FAX_0 AS fax, B.WEB_1 AS mail, N.DAYLTI_0 AS nbr_JrTransit, N.ROWID AS ID
FROM     DELADEV.BPCUSTOMER AS A INNER JOIN
                  DELADEV.BPADDRESS AS B ON A.BPCNUM_0 = B.BPANUM_0 AND A.BPAADD_0 = B.BPAADD_0 INNER JOIN
                  DELADEV.BPDLVCUST AS N ON A.BPCNUM_0 = N.BPCNUM_0
WHERE  (A.BCGCOD_0 LIKE 'CE')

--YNCOL

SELECT YITMREF_0, COL
FROM     dbo.YCOL
WHERE  (COL IS NOT NULL)


--YNPAL

SELECT YITMREF_0, PAL
FROM     dbo.YPAL
WHERE  (PAL IS NOT NULL)

----YNPC


SELECT P.YITMREF_0, CASE WHEN P.[PAL] NOT LIKE 'NULL' AND C.[COL] NOT LIKE 'NULL' THEN P.PAL END AS PAL, CASE WHEN P.[PAL] NOT LIKE 'NULL' AND C.[COL] NOT LIKE 'NULL' THEN C.[COL] END AS COL
FROM     dbo.YPAL AS P INNER JOIN
                  dbo.YCOL AS C ON P.YITMREF_0 = C.YITMREF_0
WHERE  (P.PAL IS NOT NULL) AND (C.COL IS NOT NULL)

----YNPFV


SELECT B.YPF1_0 AS Code_sku, 'Article' AS Nature, CASE WHEN C.[YNV2_0] LIKE 'PACK%' THEN E.[YNP2_0] ELSE C.[YNV2_0] END AS Code_art, CASE WHEN C.[YNV2_0] LIKE 'PACK%' THEN E.[YBQTY_0] ELSE C.[YQTY_0] END AS qte_art, 
                  CASE WHEN C.[YNV1_0] LIKE 'SKU%' THEN 'COL' WHEN C.[YNV1_0] LIKE 'PAL%' THEN 'PAL' END AS destock, CASE WHEN C.[YNV2_0] LIKE 'PACK%' THEN E.[YSCA_0] ELSE C.[YSCA_0] END AS prctg_maj, 
                  CASE WHEN C.[YNV2_0] LIKE 'PACK%' THEN E.[YID_0] ELSE C.[YID_0] END AS IDPK
FROM     DELADEV.YSKU AS C LEFT OUTER JOIN
                  DELADEV.YPACK AS E ON C.YNV2_0 = E.YNP1_0 INNER JOIN
                  DELADEV.YPFV AS B ON C.YNV1_0 = B.YPV2_0

----YPAL

SELECT YITMREF_0, CASE WHEN U.[YCOND_0] LIKE '%PAL%' AND U.[YUNI_0] LIKE '%COL%' THEN U.[YVAL_0] END AS PAL
FROM     DELADEV.YCOUNIT AS U
WHERE  (YITMREF_0 LIKE 'PFV%')

----YPK


SELECT V.YPF1_0, U.YNV1_0, D.YFILM_0
FROM     DELADEV.YSKU AS U INNER JOIN
                  DELADEV.YPFV AS V ON U.YNV1_0 = V.YPV2_0 INNER JOIN
                  DELADEV.BOM AS D ON D.ITMREF_0 = U.YNV2_0
WHERE  (U.YNV1_0 LIKE 'SKU%') AND (U.YNV2_0 LIKE 'PACK%')

----YTYP

SELECT S.YPF1_0, S.YPV2_0, A.LANMES_0
FROM     DELADEV.YPFV AS S INNER JOIN
                  DELADEV.ITMMASTER AS K ON S.YPV2_0 = K.ITMREF_0 INNER JOIN
                  DELADEV.APLSTD AS A ON A.LANNUM_0 = K.YLOPRE_0
WHERE  (S.YPV2_0 LIKE 'SKU%') AND (A.LANCHP_0 = 6152)

----YVPFV

SELECT B.YPF1_0 AS Code_sku, CASE WHEN C.[YNV2_0] LIKE 'PACK%' THEN E.[YNP2_0] WHEN C.[YNV2_0] NOT LIKE 'PACK%' THEN C.[YNV2_0] END AS Code_art, 
                  CASE WHEN C.[YNV1_0] LIKE 'SKU%' THEN 'COL' WHEN C.[YNV1_0] LIKE 'PAL%' THEN 'PAL' END AS destock
FROM     DELADEV.YSKU AS C LEFT OUTER JOIN
                  DELADEV.YPACK AS E ON C.YNV2_0 = E.YNP1_0 INNER JOIN
                  DELADEV.YPFV AS B ON C.YNV1_0 = B.YPV2_0

----Ycmd_annuelle


SELECT B.YPSNUM_0 AS num_prog, CAST(A.LANMES_0 AS VARCHAR) + ' ' + B.YCAMPAGNE_0 AS cod_camp, B.YCLIENT_0 AS cod_cli, 0 AS cod_contrat, 'Palette' AS typ, 0 AS jr_trans, B.YITMREF_0 AS cod_sku, B.YWEEK_0 AS num_sem, 
                  B.YDATSEM_0 AS dte_debutSem, B.YENGENNBR_0 AS quantite, B.YQTY_0 AS pds_com, 0 AS version, B.ROWID AS ID
FROM     DELADEV.YPLASIMD AS B INNER JOIN
                  DELADEV.APLSTD AS A ON A.LANNUM_0 = B.YSAISONDD_0 INNER JOIN
                  DELADEV.YPLASIMH AS c ON B.YPSNUM_0 = c.YPSNUM_0
WHERE  (A.LANCHP_0 = '6124') AND (c.YPSSTA_0 = 2)

----ycmd_hebdo


SELECT R.SOHNUM_0 AS num_cmd, R.ORDDAT_0 AS dte_cmd, R.SHIDAT_0 AS dte_dep, R.BPCORD_0 AS cod_cli, R.CUSORDREF_0 AS num_PO, R.BPAADD_0 AS adres_liv, R.DEMDLVDAT_0 AS dte_arrive, R.DAYLTI_0 AS transit_time, 
                  1 AS version, 'Initiale' AS etat, 'Non' AS valid, SUM(Q.QTY_0 / P.PAL) AS nbr_pal, SUM(Q.QTY_0) AS nbr_col, SUM(Q.QTY_0 * C.COL) AS pds_prod, SUM(Q.QTY_0 * C.COL) AS pds_com
FROM     DELADEV.SORDER AS R INNER JOIN
                  DELADEV.SORDERQ AS Q ON Q.SOHNUM_0 = R.SOHNUM_0 INNER JOIN
                  dbo.YNPAL AS P ON P.YITMREF_0 = Q.ITMREF_0 INNER JOIN
                  dbo.YNCOL AS C ON C.YITMREF_0 = Q.ITMREF_0
WHERE  (R.BETFCY_0 = 1)
GROUP BY R.SOHNUM_0, R.ORDDAT_0, R.SHIDAT_0, R.BPCORD_0, R.CUSORDREF_0, R.BPAADD_0, R.DEMDLVDAT_0, R.DAYLTI_0

----YSKU


SELECT I.ITMREF_0 AS YNV1_0, B.CPNITMREF_0 AS YNV2_0, B.BOMQTY_0 AS YQTY_0, B.SCA_0 AS YSCA_0, B.ROWID AS YID_0
FROM     DELADEV.BOMD AS B LEFT OUTER JOIN
                  DELADEV.ITMMASTER AS I ON I.ITMREF_0 = B.ITMREF_0
WHERE  (B.ITMREF_0 IN
                      (SELECT B.CPNITMREF_0
                       FROM      DELADEV.BOM AS A INNER JOIN
                                         DELADEV.BOMD AS B ON A.ITMREF_0 = B.ITMREF_0 INNER JOIN
                                         DELADEV.ITMMASTER AS I ON I.ITMREF_0 = B.ITMREF_0
                       WHERE   (A.BOMALT_0 = 40) AND (A.ITMREF_0 LIKE 'PFV%')))

----YPFV

SELECT B.ITMREF_0 AS YPF1_0, B.CPNITMREF_0 AS YPV2_0
FROM     DELADEV.BOM AS A INNER JOIN
                  DELADEV.BOMD AS B ON A.ITMREF_0 = B.CPNITMREF_0
WHERE  (A.BOMALT_0 = 40) AND (B.ITMREF_0 LIKE 'PFV%')


----YPACK


SELECT A.ITMREF_0 AS YNP1_0, B.CPNITMREF_0 AS YNP2_0, B.BOMQTY_0 AS YBQTY_0, B.SCA_0 AS YSCA_0, B.ROWID AS YID_0
FROM     DELADEV.BOM AS A INNER JOIN
                  DELADEV.BOMD AS B ON A.ITMREF_0 = B.ITMREF_0 INNER JOIN
                  DELADEV.ITMMASTER AS I ON I.ITMREF_0 = B.ITMREF_0
WHERE  (A.BOMALT_0 = 40) AND (A.ITMREF_0 LIKE 'PACK%')

--